garmin.activities.datasource.url=jdbc:sqlite:/home/garmindb/HealthData/DBs/garmin_activities.db
garmin.health.datasource.url=jdbc:sqlite:/home/garmindb/HealthData/DBs/garmin.db
garmin.monitoring.datasource.url=jdbc:sqlite:/home/garmindb/HealthData/DBs/garmin_monitoring.db
garmin.sync.python.path=/opt/garmindb-venv/bin/python3
garmin.sync.script.path=/opt/garmindb-venv/bin/garmindb_cli.py
server.port=8080
spring.security.oauth2.resourceserver.jwt.issuer-uri=${ISSUER_URI}
server.forward-headers-strategy=framework
management.endpoint.health.probes.enabled=true
management.health.livenessState.enabled=true
management.health.readinessState.enabled=true